import { Types } from 'mongoose';

const mockUsers = [
  {
    _id: new Types.ObjectId('651a1e9f8f1b2c001d3b0a1b'),
    firstName: 'John',
    lastName: 'Doe',
    email: 'user@example.com',
    password: 'hashedPassword',
    description: 'Just started playing',
    birthdate: new Date(),
    isAvailable: true,
    address: 'Main road 2, Odense',
    phoneNumber: '5739603',
    image: 'imageurl',
    lastLoggedIn: new Date(),
    createdAt: new Date(),
    isNewsletter: false,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('651a1e9f8f1b2c001d3b0a1c'),
    firstName: 'Emil',
    lastName: 'D.',
    email: 'emil@example.com',
    password: 'hashedPassword',
    birthdate: new Date(),
    isAvailable: false,
    address: 'Main road 2, Copenhagen',
    phoneNumber: '5739305',
    image: 'imageurl',
    lastLoggedIn: new Date(),
    createdAt: new Date(),
    isNewsletter: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('651a1e9f8f1b2c001d3b0a12'),
    firstName: 'Katherine',
    lastName: 'S.',
    email: 'katherine@example.com',
    password: 'hashedPassword',
    birthdate: new Date(),
    isAvailable: true,
    address: 'Kings street 4, Copenhagen',
    phoneNumber: '3958200',
    image: 'imageurl',
    lastLoggedIn: new Date(),
    createdAt: new Date(),
    isNewsletter: false,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('651a1e9f8f1b2c001d3b0a10'),
    firstName: 'Emma',
    lastName: 'F.',
    email: 'emma@example.com',
    password: 'hashedPassword',
    birthdate: new Date(),
    isAvailable: true,
    address: 'High road 32, Aarhus',
    phoneNumber: '94830256',
    image: 'imageurl',
    lastLoggedIn: new Date(),
    createdAt: new Date(),
    isNewsletter: true,
    isDeleted: false,
  },
  {
    _id: new Types.ObjectId('651a1e9f8f1b2c001d3b0a17'),
    firstName: 'Anders',
    lastName: 'T.',
    email: 'anders@example.com',
    password: 'hashedPassword',
    birthdate: new Date(),
    isAvailable: false,
    address: 'New plaza 78b, Copenhagen',
    phoneNumber: '48302859',
    image: 'imageurl',
    lastLoggedIn: new Date(),
    createdAt: new Date(),
    isNewsletter: false,
    isDeleted: false,
  },
];

export default mockUsers;
